### ISSUE TITLE
Matlab run ROMEO error

### ISSUE THREAD

**Issue by XYWCQM** [korbinian90/ROMEO#17] opened 2023-11-23 11:04 UTC
**Hello:
  I plan to carry out phase unwrapping through ROMEO, but the following errors are reported during operation (my matlab version is R2020a, mritools windows is v4.0.2) :**

_ROMEO command: "C:\Users\wang\Desktop\my_QSM_calc\mritools_windows-2019_4.0.2\matlab\..\bin\romeo.exe" "-p" "C:\Users\wang\Desktop\my_QSM_calc\Head_QSM_193459\QSM_results\phase_unwapping\Phase.nii" "-o" "C:\Users\wang\Desktop\my_QSM_calc\Head_QSM_193459\QSM_results\phase_unwapping\Unwrapped.nii" "-B" "-m" "C:\Users\wang\Desktop\my_QSM_calc\Head_QSM_193459\QSM_results\phase_unwapping\Mag.nii" "-t" "[6.8 14 21.2 28.4 35.6]" "-k" "C:\Users\wang\Desktop\my_QSM_calc\Head_QSM_193459\QSM_results\phase_unwapping\Mask.nii" --verbose -q
fatal: error thrown and no exception handler available.
InitError(mod=:GPUCompiler, error=ErrorException("type Nothing has no field major"))
ijl_errorf at C:/workdir/src\rtutils.c:77
ijl_has_no_field_error at C:/workdir/src\rtutils.c:137
getproperty at .\Base.jl:37
__init__ at C:\Users\runneradmin\.julia\packages\GPUCompiler\2mJjc\src\GPUCompiler.jl:64
jfptr___init___99249.clone_1 at C:\Users\wang\Desktop\my_QSM_calc\mritools_windows-2019_4.0.2\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1880 [inlined]
jl_module_run_initializer at C:/workdir/src\toplevel.c:75
_finish_julia_init at C:/workdir/src\init.c:855
ijl_init_with_image at C:/workdir/src\jlapi.c:66 [inlined]
ijl_init_with_image at C:/workdir/src\jlapi.c:55 [inlined]
ijl_init at C:/workdir/src\jlapi.c:82
.text at C:\Users\wang\Desktop\my_QSM_calc\mritools_windows-2019_4.0.2\bin\romeo.exe (unknown line)
__tmainCRTStartup at C:\Users\wang\Desktop\my_QSM_calc\mritools_windows-2019_4.0.2\bin\romeo.exe (unknown line)
.l_start at C:\Users\wang\Desktop\my_QSM_calc\mritools_windows-2019_4.0.2\bin\romeo.exe (unknown line)
BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
错误使用 ROMEO (line 89)
Something went wrong!
Please also try if ROMEO works via the command line.
Otherwise, please report the issue on https://github.com/korbinian90/ROMEO/issues

出错 Format_conversion (line 123)
[unwrapped, B0] = ROMEO(Phase_nii.img, parameters);_

**I run romeo.exe on the command line to get the same error, what should I do next, thank you.**

**Comment by korbinian90** [comment] 2023-11-23 12:46
Thank you for reporting this problem!
I could reproduce it, but don't know yet why the new build failed for windows.

Until I figured out the problem and upload an updated version, you can try this version: https://github.com/korbinian90/CompileMRI.jl/releases/tag/v3.6.6

(This older version doesn't yet include this matlab fix, but you can add it to the matlab caller in case there is a problem: https://github.com/korbinian90/ROMEO#issues-when-calling-from-matlab)

**Comment by XYWCQM** [comment] 2023-11-24 02:02
**Thanks for your reply, I'll try.**

**Comment by korbinian90** [comment] 2023-12-06 07:47
This should be fixed in the new release 4.0.6
Please reopen, if the issue is not fixed for you. Thank you

**Closed as completed by korbinian90** 2023-12-06 07:47 UTC
